name: Ktp
version: '1.0-SNAPSHOT'
main: org.jt.ktp.Ktp
api-version: '1.20'
authors: [ jajader ]
description: I really want to Maze

commands:
  Maze:
    description: Testing
    usage: testing

  SW:
    description: Testing
    usage: testing
